#!/bin/sh

#
# Use these scripts when developing and testing changes to solvahol/dns.
#
# - script/bootstrap: Ensure this workspace is ready.
#

# Work from the root of a Git repository.
cd "$(git rev-parse --show-toplevel)" || \
echo "WARN: Unable to cd to repository root."

# Required commands are available.
for _thiscmd in docker git; do
  command -v ${_thiscmd} >/dev/null 2>&1 || echo "WARN: Missing ${_thiscmd}."
done

# Required files are present, readable, and not empty.
for _thisfile in public.yaml .config; do
  if [ ! -s "${_thisfile}" ] && [ ! -r "${_thisfile}" ]; then
    echo "WARN: Missing ${_thisfile}."
  fi
done

# Set environment variables.
. ./.config || echo "WARN: Unable to run .config."

# Ensure Docker is present and working; Pull the image we'll use.
if command -v docker >/dev/null 2>&1 && [ -n "${_image}" ]; then
  docker pull "${_image}"
else
  echo ""
  echo "Hmm. Something isn't right. Does this work for you?:"
  echo "docker pull \"${_image}\""
  echo ""
fi
