#!/bin/sh

#
# Use these scripts to (test and) deploy the octodns config in this repository.
#
# - script/cibuild: Install octodns and dependencies.
#

# Run relative to $GITHUB_WORKSPACE in Actions runner, or fail.
if [ -n "${GITHUB_WORKSPACE}" ]; then
  cd "${GITHUB_WORKSPACE}" || exit 2
else
  echo "FAIL: \$GITHUB_WORKSPACE is not set."
  exit 1
fi

# Upgrade pip to ensure compatibility.
python -m pip install --upgrade pip

# Install all the (versioned) packages octodns may require.
pip install -r octodns/requirements.txt

# Install octodns.
pip install ./octodns
