#!/bin/sh

#
# Use these scripts to (test and) deploy the octodns config in this repository.
#
# - script/console: Run a shell in the octodns-action container.
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

# Set environment variables.
. ./.config

# Start a shell in an octodns-action container, with our config mounted.
if command -v docker >/dev/null 2>&1; then
  docker run --rm -v "${_volume}":"${_mountpoint}":ro \
  --env-file "${_env_path}" --entrypoint /bin/sh "${_image}"
else
  echo " "
  echo "Did not find docker. Run this command:"
  echo "docker run --rm -v \"${_volume}\":\"${_mountpoint}\":ro \\"
  echo "--env-file \"${_env_path}\" --entrypoint /bin/sh \"${_image}\""
  echo " "
fi
