#!/bin/sh

#
# Use these scripts when developing and testing changes to solvahol/dns.
#
# - script/console: Run a shell in an octodns-sync container.
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

# Set environment variables.
. ./.config

# Start a shell in an octodns-sync container, with our config mounted.
if command -v docker >/dev/null 2>&1; then
  docker run -it --rm -v "${_volume}":"${_mountpoint}":ro \
  --env-file "${_env_path}" --entrypoint /bin/bash "${_image}"
else
  echo " "
  echo "Did not find docker. Run this command:"
  echo "docker run --rm -v \"${_volume}\":\"${_mountpoint}\":ro \\"
  echo "--env-file \"${_env_path}\" --entrypoint /bin/bash \"${_image}\""
  echo " "
fi
