#!/bin/sh

#
# Use these scripts when developing and testing changes to solvahol/dns.
#
# - script/test: Test this version of the configuration.
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

# Set environment variables.
. ./.config

# - Lint all the things.
./test/00_linters

# - Test our configs.
./test/10_test-config public.yaml
