name: octodns-sync

on:
  # Run when changes are pushed to any pull request
  pull_request:
    paths:
      - '*.yaml'
  # Note: Running workflows on pull_request_target can be dangerous!
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

  # Run when manually triggered
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  deployments: write
  issues: write
  packages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: write

defaults:
  run:
    shell: bash

env:
  CONFIG_TO_USE: public.yaml

jobs:

  meta:
    name: Parse event data into outputs
    runs-on: ubuntu-20.04
    outputs:
      config: ${{ steps.which-config.outputs.config }}
      ref: ${{ steps.get-ref.outputs.ref }}
      sha: ${{ steps.get-sha.outputs.sha }}
    steps:
      - name: Checkout ${{ github.repository }}:${{ github.ref }}
        uses: actions/checkout@v3
      - name: 'which-config: Which config file to run?'
        id: which-config
        run: |
          _config="${{ env.CONFIG_TO_USE }}"
          echo "::set-output name=config::${_config}"
      - name: 'ref: The Git ref to read config from'
        id: get-ref
        run: |
          case "${{ github.event_name }}" in
            "pull_request")
              _ref=refs/pull/${{ github.event.pull_request.number }}/merge ;;
            "issue_comment")
              _ref=refs/pull/${{ github.event.issue.number }}/merge ;;
            *)
              _ref=${{ github.ref }}
          esac
          echo "::set-output name=ref::${_ref}"
      - name: 'sha: A short SHA of the commit to read config from'
        id: get-sha
        run: |
          git fetch origin ${{ steps.get-ref.outputs.ref }}
          _sha=$(cut -c 1-8 .git/FETCH_HEAD)
          echo "::set-output name=sha::${_sha}"

  validate:
    name: Validate ${{ needs.meta.outputs.config }}, plan for changes
    needs: meta
    environment: test
    runs-on: ubuntu-20.04
    outputs:
      plan: ${{ steps.octodns-sync.outputs.plan }}
    steps:
      - name: Checkout ${{ github.repository }}:${{ needs.meta.outputs.ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.meta.outputs.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run `octodns-sync` with ${{ needs.meta.outputs.config }}
        id: octodns-sync
        uses: solvaholic/octodns-sync@issue92
        # TODO: When no changes, skip the rest of this workflow?
        with:
          config_path: ${{ needs.meta.outputs.config }}
        env:
          AZURE_APPLICATION_ID: ${{ secrets.azure_application_id }}
          AZURE_AUTHENTICATION_KEY: ${{ secrets.azure_authentication_key }}
          AZURE_DIRECTORY_ID: ${{ secrets.azure_directory_id }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.azure_subscription_id }}

  comment:
    name: Add ${{ needs.meta.outputs.config }} plan to PR comment
    needs: [meta, validate]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Find previous comment, if present
        uses: peter-evans/find-comment@v2.2.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: Automatically generated by octodns-sync
      - name: Create or update comment
        id: prcomment
        uses: peter-evans/create-or-update-comment@v2.0.1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## OctoDNS Plan for `${{ needs.meta.outputs.sha }}`

            ${{ needs.validate.outputs.plan }}

            Automatically generated by octodns-sync
          edit-mode: replace
